# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest


stages:
- stage : first
  displayName: Download spring3hibernate Artifact
  jobs:
  - job:
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'e293d92f-195c-46e7-9d7d-034da48008d8'
        definition: '12'
        specificBuildWithTriggering: true
        buildVersionToDownload: 'latest'
        artifactName: 'Spring3HibernateApp'
        targetPath: '$(System.DefaultWorkingDirectory)'
    - bash: scp Spring3HibernateApp.war ubuntu@18.118.51.233:/var/lib/tomcat9/webapps/ROOT/

